# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Kelvin Tse
email:
description: > # this means to ignore newlines until "baseurl:"
  Vehicle dynamics from scratch. Real life applications in vehicle dynamics
  from an engineering and technology perspective.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://kktse.github.io" # the base hostname & protocol for your site, e.g. http://example.com
permalink: /jekyll/update/:year/:month/:day/:title:output_ext

# Build settings
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

whitelist:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-redirect-from
  - jemoji

# Theme settings
minima:
  skin: classic
  social_links:
    - { platform: github, user_url: "https://github.com/kktse" }
    - { platform: linkedin, user_url: "https://www.linkedin.com/in/ktse/" }

use_mathjax: true

author:
  name: Kelvin Tse
  email: ""

header_pages:
  - home.md
  - categories.html
  - about.md

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Google Analytics
google_analytics: "UA-103417873-1"
